// Generated by gencpp from file commande_locale/Msg_Color.msg
// DO NOT EDIT!


#ifndef COMMANDE_LOCALE_MESSAGE_MSG_COLOR_H
#define COMMANDE_LOCALE_MESSAGE_MSG_COLOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace commande_locale
{
template <class ContainerAllocator>
struct Msg_Color_
{
  typedef Msg_Color_<ContainerAllocator> Type;

  Msg_Color_()
    : header()
    , Handle(0)
    , Color(0)  {
    }
  Msg_Color_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , Handle(0)
    , Color(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _Handle_type;
  _Handle_type Handle;

   typedef int32_t _Color_type;
  _Color_type Color;





  typedef boost::shared_ptr< ::commande_locale::Msg_Color_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::commande_locale::Msg_Color_<ContainerAllocator> const> ConstPtr;

}; // struct Msg_Color_

typedef ::commande_locale::Msg_Color_<std::allocator<void> > Msg_Color;

typedef boost::shared_ptr< ::commande_locale::Msg_Color > Msg_ColorPtr;
typedef boost::shared_ptr< ::commande_locale::Msg_Color const> Msg_ColorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::commande_locale::Msg_Color_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::commande_locale::Msg_Color_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace commande_locale

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'commande_locale': ['/home/firerazzer/Documents/TER/MONTRAC/catkin_ws/src/commande_locale/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::commande_locale::Msg_Color_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::commande_locale::Msg_Color_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commande_locale::Msg_Color_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commande_locale::Msg_Color_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commande_locale::Msg_Color_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commande_locale::Msg_Color_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::commande_locale::Msg_Color_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bc181530e810a3c987e52bb86805fe8b";
  }

  static const char* value(const ::commande_locale::Msg_Color_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbc181530e810a3c9ULL;
  static const uint64_t static_value2 = 0x87e52bb86805fe8bULL;
};

template<class ContainerAllocator>
struct DataType< ::commande_locale::Msg_Color_<ContainerAllocator> >
{
  static const char* value()
  {
    return "commande_locale/Msg_Color";
  }

  static const char* value(const ::commande_locale::Msg_Color_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::commande_locale::Msg_Color_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
int32 Handle\n\
int32 Color\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::commande_locale::Msg_Color_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::commande_locale::Msg_Color_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.Handle);
      stream.next(m.Color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Msg_Color_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::commande_locale::Msg_Color_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::commande_locale::Msg_Color_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "Handle: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Handle);
    s << indent << "Color: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMANDE_LOCALE_MESSAGE_MSG_COLOR_H
