// Generated by gencpp from file commande_locale/Msg_Erreur.msg
// DO NOT EDIT!


#ifndef COMMANDE_LOCALE_MESSAGE_MSG_ERREUR_H
#define COMMANDE_LOCALE_MESSAGE_MSG_ERREUR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace commande_locale
{
template <class ContainerAllocator>
struct Msg_Erreur_
{
  typedef Msg_Erreur_<ContainerAllocator> Type;

  Msg_Erreur_()
    : code(0)
    , n_poste(0)  {
    }
  Msg_Erreur_(const ContainerAllocator& _alloc)
    : code(0)
    , n_poste(0)  {
  (void)_alloc;
    }



   typedef int32_t _code_type;
  _code_type code;

   typedef int32_t _n_poste_type;
  _n_poste_type n_poste;





  typedef boost::shared_ptr< ::commande_locale::Msg_Erreur_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::commande_locale::Msg_Erreur_<ContainerAllocator> const> ConstPtr;

}; // struct Msg_Erreur_

typedef ::commande_locale::Msg_Erreur_<std::allocator<void> > Msg_Erreur;

typedef boost::shared_ptr< ::commande_locale::Msg_Erreur > Msg_ErreurPtr;
typedef boost::shared_ptr< ::commande_locale::Msg_Erreur const> Msg_ErreurConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::commande_locale::Msg_Erreur_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::commande_locale::Msg_Erreur_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace commande_locale

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'commande_locale': ['/home/firerazzer/Documents/TER/MONTRAC/catkin_ws/src/commande_locale/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::commande_locale::Msg_Erreur_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::commande_locale::Msg_Erreur_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commande_locale::Msg_Erreur_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commande_locale::Msg_Erreur_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commande_locale::Msg_Erreur_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commande_locale::Msg_Erreur_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::commande_locale::Msg_Erreur_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81853f895108ea47877f09e6d08519dc";
  }

  static const char* value(const ::commande_locale::Msg_Erreur_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81853f895108ea47ULL;
  static const uint64_t static_value2 = 0x877f09e6d08519dcULL;
};

template<class ContainerAllocator>
struct DataType< ::commande_locale::Msg_Erreur_<ContainerAllocator> >
{
  static const char* value()
  {
    return "commande_locale/Msg_Erreur";
  }

  static const char* value(const ::commande_locale::Msg_Erreur_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::commande_locale::Msg_Erreur_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 code\n\
int32 n_poste\n\
";
  }

  static const char* value(const ::commande_locale::Msg_Erreur_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::commande_locale::Msg_Erreur_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.code);
      stream.next(m.n_poste);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Msg_Erreur_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::commande_locale::Msg_Erreur_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::commande_locale::Msg_Erreur_<ContainerAllocator>& v)
  {
    s << indent << "code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.code);
    s << indent << "n_poste: ";
    Printer<int32_t>::stream(s, indent + "  ", v.n_poste);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMANDE_LOCALE_MESSAGE_MSG_ERREUR_H
