// Generated by gencpp from file commande_locale/SrvAddProductPushBackRequest.msg
// DO NOT EDIT!


#ifndef COMMANDE_LOCALE_MESSAGE_SRVADDPRODUCTPUSHBACKREQUEST_H
#define COMMANDE_LOCALE_MESSAGE_SRVADDPRODUCTPUSHBACKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace commande_locale
{
template <class ContainerAllocator>
struct SrvAddProductPushBackRequest_
{
  typedef SrvAddProductPushBackRequest_<ContainerAllocator> Type;

  SrvAddProductPushBackRequest_()
    : poste(0)
    , produit(0)  {
    }
  SrvAddProductPushBackRequest_(const ContainerAllocator& _alloc)
    : poste(0)
    , produit(0)  {
  (void)_alloc;
    }



   typedef int32_t _poste_type;
  _poste_type poste;

   typedef int32_t _produit_type;
  _produit_type produit;





  typedef boost::shared_ptr< ::commande_locale::SrvAddProductPushBackRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::commande_locale::SrvAddProductPushBackRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SrvAddProductPushBackRequest_

typedef ::commande_locale::SrvAddProductPushBackRequest_<std::allocator<void> > SrvAddProductPushBackRequest;

typedef boost::shared_ptr< ::commande_locale::SrvAddProductPushBackRequest > SrvAddProductPushBackRequestPtr;
typedef boost::shared_ptr< ::commande_locale::SrvAddProductPushBackRequest const> SrvAddProductPushBackRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::commande_locale::SrvAddProductPushBackRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::commande_locale::SrvAddProductPushBackRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace commande_locale

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'commande_locale': ['/home/firerazzer/Documents/TER/MONTRAC/catkin_ws/src/commande_locale/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::commande_locale::SrvAddProductPushBackRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::commande_locale::SrvAddProductPushBackRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commande_locale::SrvAddProductPushBackRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commande_locale::SrvAddProductPushBackRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commande_locale::SrvAddProductPushBackRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commande_locale::SrvAddProductPushBackRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::commande_locale::SrvAddProductPushBackRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3039ca7d9d039656971a53824ad295d1";
  }

  static const char* value(const ::commande_locale::SrvAddProductPushBackRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3039ca7d9d039656ULL;
  static const uint64_t static_value2 = 0x971a53824ad295d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::commande_locale::SrvAddProductPushBackRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "commande_locale/SrvAddProductPushBackRequest";
  }

  static const char* value(const ::commande_locale::SrvAddProductPushBackRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::commande_locale::SrvAddProductPushBackRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 poste\n\
int32 produit\n\
";
  }

  static const char* value(const ::commande_locale::SrvAddProductPushBackRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::commande_locale::SrvAddProductPushBackRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.poste);
      stream.next(m.produit);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SrvAddProductPushBackRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::commande_locale::SrvAddProductPushBackRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::commande_locale::SrvAddProductPushBackRequest_<ContainerAllocator>& v)
  {
    s << indent << "poste: ";
    Printer<int32_t>::stream(s, indent + "  ", v.poste);
    s << indent << "produit: ";
    Printer<int32_t>::stream(s, indent + "  ", v.produit);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMANDE_LOCALE_MESSAGE_SRVADDPRODUCTPUSHBACKREQUEST_H
