// Generated by gencpp from file commande_locale/SrvFinInit.msg
// DO NOT EDIT!


#ifndef COMMANDE_LOCALE_MESSAGE_SRVFININIT_H
#define COMMANDE_LOCALE_MESSAGE_SRVFININIT_H

#include <ros/service_traits.h>


#include <commande_locale/SrvFinInitRequest.h>
#include <commande_locale/SrvFinInitResponse.h>


namespace commande_locale
{

struct SrvFinInit
{

typedef SrvFinInitRequest Request;
typedef SrvFinInitResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SrvFinInit
} // namespace commande_locale


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::commande_locale::SrvFinInit > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::commande_locale::SrvFinInit&) { return value(); }
};

template<>
struct DataType< ::commande_locale::SrvFinInit > {
  static const char* value()
  {
    return "commande_locale/SrvFinInit";
  }

  static const char* value(const ::commande_locale::SrvFinInit&) { return value(); }
};


// service_traits::MD5Sum< ::commande_locale::SrvFinInitRequest> should match 
// service_traits::MD5Sum< ::commande_locale::SrvFinInit > 
template<>
struct MD5Sum< ::commande_locale::SrvFinInitRequest>
{
  static const char* value()
  {
    return MD5Sum< ::commande_locale::SrvFinInit >::value();
  }
  static const char* value(const ::commande_locale::SrvFinInitRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::commande_locale::SrvFinInitRequest> should match 
// service_traits::DataType< ::commande_locale::SrvFinInit > 
template<>
struct DataType< ::commande_locale::SrvFinInitRequest>
{
  static const char* value()
  {
    return DataType< ::commande_locale::SrvFinInit >::value();
  }
  static const char* value(const ::commande_locale::SrvFinInitRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::commande_locale::SrvFinInitResponse> should match 
// service_traits::MD5Sum< ::commande_locale::SrvFinInit > 
template<>
struct MD5Sum< ::commande_locale::SrvFinInitResponse>
{
  static const char* value()
  {
    return MD5Sum< ::commande_locale::SrvFinInit >::value();
  }
  static const char* value(const ::commande_locale::SrvFinInitResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::commande_locale::SrvFinInitResponse> should match 
// service_traits::DataType< ::commande_locale::SrvFinInit > 
template<>
struct DataType< ::commande_locale::SrvFinInitResponse>
{
  static const char* value()
  {
    return DataType< ::commande_locale::SrvFinInit >::value();
  }
  static const char* value(const ::commande_locale::SrvFinInitResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMANDE_LOCALE_MESSAGE_SRVFININIT_H
