// Generated by gencpp from file plc_out/outputsResponse.msg
// DO NOT EDIT!


#ifndef PLC_OUT_MESSAGE_OUTPUTSRESPONSE_H
#define PLC_OUT_MESSAGE_OUTPUTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace plc_out
{
template <class ContainerAllocator>
struct outputsResponse_
{
  typedef outputsResponse_<ContainerAllocator> Type;

  outputsResponse_()
    : feedback_out()  {
    }
  outputsResponse_(const ContainerAllocator& _alloc)
    : feedback_out(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _feedback_out_type;
  _feedback_out_type feedback_out;





  typedef boost::shared_ptr< ::plc_out::outputsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plc_out::outputsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct outputsResponse_

typedef ::plc_out::outputsResponse_<std::allocator<void> > outputsResponse;

typedef boost::shared_ptr< ::plc_out::outputsResponse > outputsResponsePtr;
typedef boost::shared_ptr< ::plc_out::outputsResponse const> outputsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plc_out::outputsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plc_out::outputsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace plc_out

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::plc_out::outputsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plc_out::outputsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plc_out::outputsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plc_out::outputsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plc_out::outputsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plc_out::outputsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plc_out::outputsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fcdceee3a74b2fb5d19ad48da0766c7f";
  }

  static const char* value(const ::plc_out::outputsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfcdceee3a74b2fb5ULL;
  static const uint64_t static_value2 = 0xd19ad48da0766c7fULL;
};

template<class ContainerAllocator>
struct DataType< ::plc_out::outputsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plc_out/outputsResponse";
  }

  static const char* value(const ::plc_out::outputsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plc_out::outputsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string feedback_out\n\
\n\
";
  }

  static const char* value(const ::plc_out::outputsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plc_out::outputsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback_out);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct outputsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plc_out::outputsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plc_out::outputsResponse_<ContainerAllocator>& v)
  {
    s << indent << "feedback_out: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.feedback_out);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLC_OUT_MESSAGE_OUTPUTSRESPONSE_H
