// Generated by gencpp from file plc_in/inputsResponse.msg
// DO NOT EDIT!


#ifndef PLC_IN_MESSAGE_INPUTSRESPONSE_H
#define PLC_IN_MESSAGE_INPUTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace plc_in
{
template <class ContainerAllocator>
struct inputsResponse_
{
  typedef inputsResponse_<ContainerAllocator> Type;

  inputsResponse_()
    : feedback_in()  {
    }
  inputsResponse_(const ContainerAllocator& _alloc)
    : feedback_in(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _feedback_in_type;
  _feedback_in_type feedback_in;




  typedef boost::shared_ptr< ::plc_in::inputsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plc_in::inputsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct inputsResponse_

typedef ::plc_in::inputsResponse_<std::allocator<void> > inputsResponse;

typedef boost::shared_ptr< ::plc_in::inputsResponse > inputsResponsePtr;
typedef boost::shared_ptr< ::plc_in::inputsResponse const> inputsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plc_in::inputsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plc_in::inputsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace plc_in

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::plc_in::inputsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plc_in::inputsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plc_in::inputsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plc_in::inputsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plc_in::inputsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plc_in::inputsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plc_in::inputsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b9ea0bcecaca315be305f10ed29ab78";
  }

  static const char* value(const ::plc_in::inputsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b9ea0bcecaca315ULL;
  static const uint64_t static_value2 = 0xbe305f10ed29ab78ULL;
};

template<class ContainerAllocator>
struct DataType< ::plc_in::inputsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plc_in/inputsResponse";
  }

  static const char* value(const ::plc_in::inputsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plc_in::inputsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string feedback_in\n\
\n\
";
  }

  static const char* value(const ::plc_in::inputsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plc_in::inputsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback_in);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct inputsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plc_in::inputsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plc_in::inputsResponse_<ContainerAllocator>& v)
  {
    s << indent << "feedback_in: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.feedback_in);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLC_IN_MESSAGE_INPUTSRESPONSE_H
