# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from commande_locale/Msg_SensorState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Msg_SensorState(genpy.Message):
  _md5sum = "aa8adb758a14a53aa51fe1417a2d8e34"
  _type = "commande_locale/Msg_SensorState"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

bool[9] CPI
bool[11] CP
bool[17] PS
bool[13] DG
bool[13] DD

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  __slots__ = ['header','CPI','CP','PS','DG','DD']
  _slot_types = ['std_msgs/Header','bool[9]','bool[11]','bool[17]','bool[13]','bool[13]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,CPI,CP,PS,DG,DD

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Msg_SensorState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.CPI is None:
        self.CPI = [False,False,False,False,False,False,False,False,False]
      if self.CP is None:
        self.CP = [False,False,False,False,False,False,False,False,False,False,False]
      if self.PS is None:
        self.PS = [False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False]
      if self.DG is None:
        self.DG = [False,False,False,False,False,False,False,False,False,False,False,False,False]
      if self.DD is None:
        self.DD = [False,False,False,False,False,False,False,False,False,False,False,False,False]
    else:
      self.header = std_msgs.msg.Header()
      self.CPI = [False,False,False,False,False,False,False,False,False]
      self.CP = [False,False,False,False,False,False,False,False,False,False,False]
      self.PS = [False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False]
      self.DG = [False,False,False,False,False,False,False,False,False,False,False,False,False]
      self.DD = [False,False,False,False,False,False,False,False,False,False,False,False,False]

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_9B.pack(*self.CPI))
      buff.write(_struct_11B.pack(*self.CP))
      buff.write(_struct_17B.pack(*self.PS))
      buff.write(_struct_13B.pack(*self.DG))
      buff.write(_struct_13B.pack(*self.DD))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 9
      self.CPI = _struct_9B.unpack(str[start:end])
      self.CPI = map(bool, self.CPI)
      start = end
      end += 11
      self.CP = _struct_11B.unpack(str[start:end])
      self.CP = map(bool, self.CP)
      start = end
      end += 17
      self.PS = _struct_17B.unpack(str[start:end])
      self.PS = map(bool, self.PS)
      start = end
      end += 13
      self.DG = _struct_13B.unpack(str[start:end])
      self.DG = map(bool, self.DG)
      start = end
      end += 13
      self.DD = _struct_13B.unpack(str[start:end])
      self.DD = map(bool, self.DD)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(self.CPI.tostring())
      buff.write(self.CP.tostring())
      buff.write(self.PS.tostring())
      buff.write(self.DG.tostring())
      buff.write(self.DD.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 9
      self.CPI = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=9)
      self.CPI = map(bool, self.CPI)
      start = end
      end += 11
      self.CP = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=11)
      self.CP = map(bool, self.CP)
      start = end
      end += 17
      self.PS = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=17)
      self.PS = map(bool, self.PS)
      start = end
      end += 13
      self.DG = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=13)
      self.DG = map(bool, self.DG)
      start = end
      end += 13
      self.DD = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=13)
      self.DD = map(bool, self.DD)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_13B = struct.Struct("<13B")
_struct_3I = struct.Struct("<3I")
_struct_9B = struct.Struct("<9B")
_struct_17B = struct.Struct("<17B")
_struct_11B = struct.Struct("<11B")
