// Generated by gencpp from file plc_out/outputsRequest.msg
// DO NOT EDIT!


#ifndef PLC_OUT_MESSAGE_OUTPUTSREQUEST_H
#define PLC_OUT_MESSAGE_OUTPUTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace plc_out
{
template <class ContainerAllocator>
struct outputsRequest_
{
  typedef outputsRequest_<ContainerAllocator> Type;

  outputsRequest_()
    : data_out(0)  {
    }
  outputsRequest_(const ContainerAllocator& _alloc)
    : data_out(0)  {
  (void)_alloc;
    }



   typedef int16_t _data_out_type;
  _data_out_type data_out;




  typedef boost::shared_ptr< ::plc_out::outputsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plc_out::outputsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct outputsRequest_

typedef ::plc_out::outputsRequest_<std::allocator<void> > outputsRequest;

typedef boost::shared_ptr< ::plc_out::outputsRequest > outputsRequestPtr;
typedef boost::shared_ptr< ::plc_out::outputsRequest const> outputsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plc_out::outputsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plc_out::outputsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace plc_out

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::plc_out::outputsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plc_out::outputsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plc_out::outputsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plc_out::outputsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plc_out::outputsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plc_out::outputsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plc_out::outputsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "37a9569c32df203cc50f19c5018f9185";
  }

  static const char* value(const ::plc_out::outputsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x37a9569c32df203cULL;
  static const uint64_t static_value2 = 0xc50f19c5018f9185ULL;
};

template<class ContainerAllocator>
struct DataType< ::plc_out::outputsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plc_out/outputsRequest";
  }

  static const char* value(const ::plc_out::outputsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plc_out::outputsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 data_out\n\
";
  }

  static const char* value(const ::plc_out::outputsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plc_out::outputsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data_out);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct outputsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plc_out::outputsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plc_out::outputsRequest_<ContainerAllocator>& v)
  {
    s << indent << "data_out: ";
    Printer<int16_t>::stream(s, indent + "  ", v.data_out);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLC_OUT_MESSAGE_OUTPUTSREQUEST_H
