// Generated by gencpp from file robots/MoveRobot.msg
// DO NOT EDIT!


#ifndef ROBOTS_MESSAGE_MOVEROBOT_H
#define ROBOTS_MESSAGE_MOVEROBOT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robots
{
template <class ContainerAllocator>
struct MoveRobot_
{
  typedef MoveRobot_<ContainerAllocator> Type;

  MoveRobot_()
    : position(0)
    , bras(0)
    , pince(0)
    , num_robot(0)  {
    }
  MoveRobot_(const ContainerAllocator& _alloc)
    : position(0)
    , bras(0)
    , pince(0)
    , num_robot(0)  {
  (void)_alloc;
    }



   typedef int32_t _position_type;
  _position_type position;

   typedef int32_t _bras_type;
  _bras_type bras;

   typedef int32_t _pince_type;
  _pince_type pince;

   typedef int32_t _num_robot_type;
  _num_robot_type num_robot;





  typedef boost::shared_ptr< ::robots::MoveRobot_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robots::MoveRobot_<ContainerAllocator> const> ConstPtr;

}; // struct MoveRobot_

typedef ::robots::MoveRobot_<std::allocator<void> > MoveRobot;

typedef boost::shared_ptr< ::robots::MoveRobot > MoveRobotPtr;
typedef boost::shared_ptr< ::robots::MoveRobot const> MoveRobotConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robots::MoveRobot_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robots::MoveRobot_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robots

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robots': ['/home/firerazzer/Documents/TER/MONTRAC/catkin_ws/src/robots/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robots::MoveRobot_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robots::MoveRobot_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robots::MoveRobot_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robots::MoveRobot_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robots::MoveRobot_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robots::MoveRobot_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robots::MoveRobot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6a71d2b8fb832f571ecc6a220d76058b";
  }

  static const char* value(const ::robots::MoveRobot_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6a71d2b8fb832f57ULL;
  static const uint64_t static_value2 = 0x1ecc6a220d76058bULL;
};

template<class ContainerAllocator>
struct DataType< ::robots::MoveRobot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robots/MoveRobot";
  }

  static const char* value(const ::robots::MoveRobot_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robots::MoveRobot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 position\n\
int32 bras\n\
int32 pince\n\
int32 num_robot\n\
";
  }

  static const char* value(const ::robots::MoveRobot_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robots::MoveRobot_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.bras);
      stream.next(m.pince);
      stream.next(m.num_robot);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveRobot_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robots::MoveRobot_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robots::MoveRobot_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position);
    s << indent << "bras: ";
    Printer<int32_t>::stream(s, indent + "  ", v.bras);
    s << indent << "pince: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pince);
    s << indent << "num_robot: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_robot);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTS_MESSAGE_MOVEROBOT_H
