// Generated by gencpp from file writing_actuators/actuators.msg
// DO NOT EDIT!


#ifndef WRITING_ACTUATORS_MESSAGE_ACTUATORS_H
#define WRITING_ACTUATORS_MESSAGE_ACTUATORS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace writing_actuators
{
template <class ContainerAllocator>
struct actuators_
{
  typedef actuators_<ContainerAllocator> Type;

  actuators_()
    : actuators_data(0)  {
    }
  actuators_(const ContainerAllocator& _alloc)
    : actuators_data(0)  {
  (void)_alloc;
    }



   typedef int16_t _actuators_data_type;
  _actuators_data_type actuators_data;




  typedef boost::shared_ptr< ::writing_actuators::actuators_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::writing_actuators::actuators_<ContainerAllocator> const> ConstPtr;

}; // struct actuators_

typedef ::writing_actuators::actuators_<std::allocator<void> > actuators;

typedef boost::shared_ptr< ::writing_actuators::actuators > actuatorsPtr;
typedef boost::shared_ptr< ::writing_actuators::actuators const> actuatorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::writing_actuators::actuators_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::writing_actuators::actuators_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace writing_actuators

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'writing_actuators': ['/home/projn7cellule/cell_ros_ws/src/writing_actuators/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::writing_actuators::actuators_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::writing_actuators::actuators_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::writing_actuators::actuators_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::writing_actuators::actuators_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::writing_actuators::actuators_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::writing_actuators::actuators_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::writing_actuators::actuators_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4184e61fb7b8891ca90bb2790b008543";
  }

  static const char* value(const ::writing_actuators::actuators_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4184e61fb7b8891cULL;
  static const uint64_t static_value2 = 0xa90bb2790b008543ULL;
};

template<class ContainerAllocator>
struct DataType< ::writing_actuators::actuators_<ContainerAllocator> >
{
  static const char* value()
  {
    return "writing_actuators/actuators";
  }

  static const char* value(const ::writing_actuators::actuators_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::writing_actuators::actuators_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 actuators_data\n\
";
  }

  static const char* value(const ::writing_actuators::actuators_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::writing_actuators::actuators_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.actuators_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct actuators_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::writing_actuators::actuators_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::writing_actuators::actuators_<ContainerAllocator>& v)
  {
    s << indent << "actuators_data: ";
    Printer<int16_t>::stream(s, indent + "  ", v.actuators_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WRITING_ACTUATORS_MESSAGE_ACTUATORS_H
