// Generated by gencpp from file reading_sensors/sensors.msg
// DO NOT EDIT!


#ifndef READING_SENSORS_MESSAGE_SENSORS_H
#define READING_SENSORS_MESSAGE_SENSORS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace reading_sensors
{
template <class ContainerAllocator>
struct sensors_
{
  typedef sensors_<ContainerAllocator> Type;

  sensors_()
    : sensors_data(0)  {
    }
  sensors_(const ContainerAllocator& _alloc)
    : sensors_data(0)  {
  (void)_alloc;
    }



   typedef int16_t _sensors_data_type;
  _sensors_data_type sensors_data;




  typedef boost::shared_ptr< ::reading_sensors::sensors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reading_sensors::sensors_<ContainerAllocator> const> ConstPtr;

}; // struct sensors_

typedef ::reading_sensors::sensors_<std::allocator<void> > sensors;

typedef boost::shared_ptr< ::reading_sensors::sensors > sensorsPtr;
typedef boost::shared_ptr< ::reading_sensors::sensors const> sensorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::reading_sensors::sensors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::reading_sensors::sensors_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace reading_sensors

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'reading_sensors': ['/home/projn7cellule/cell_ros_ws/src/reading_sensors/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::reading_sensors::sensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reading_sensors::sensors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reading_sensors::sensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reading_sensors::sensors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reading_sensors::sensors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reading_sensors::sensors_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::reading_sensors::sensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1b6ffe1aca3f59adbad300aae9fa69b2";
  }

  static const char* value(const ::reading_sensors::sensors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1b6ffe1aca3f59adULL;
  static const uint64_t static_value2 = 0xbad300aae9fa69b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::reading_sensors::sensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "reading_sensors/sensors";
  }

  static const char* value(const ::reading_sensors::sensors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::reading_sensors::sensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 sensors_data\n\
";
  }

  static const char* value(const ::reading_sensors::sensors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::reading_sensors::sensors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sensors_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sensors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::reading_sensors::sensors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::reading_sensors::sensors_<ContainerAllocator>& v)
  {
    s << indent << "sensors_data: ";
    Printer<int16_t>::stream(s, indent + "  ", v.sensors_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // READING_SENSORS_MESSAGE_SENSORS_H
