// Generated by gencpp from file shuttles/shuttle_idRequest.msg
// DO NOT EDIT!


#ifndef SHUTTLES_MESSAGE_SHUTTLE_IDREQUEST_H
#define SHUTTLES_MESSAGE_SHUTTLE_IDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace shuttles
{
template <class ContainerAllocator>
struct shuttle_idRequest_
{
  typedef shuttle_idRequest_<ContainerAllocator> Type;

  shuttle_idRequest_()
    : robot(0)
    , position(0)  {
    }
  shuttle_idRequest_(const ContainerAllocator& _alloc)
    : robot(0)
    , position(0)  {
  (void)_alloc;
    }



   typedef int32_t _robot_type;
  _robot_type robot;

   typedef int32_t _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::shuttles::shuttle_idRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::shuttles::shuttle_idRequest_<ContainerAllocator> const> ConstPtr;

}; // struct shuttle_idRequest_

typedef ::shuttles::shuttle_idRequest_<std::allocator<void> > shuttle_idRequest;

typedef boost::shared_ptr< ::shuttles::shuttle_idRequest > shuttle_idRequestPtr;
typedef boost::shared_ptr< ::shuttles::shuttle_idRequest const> shuttle_idRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::shuttles::shuttle_idRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::shuttles::shuttle_idRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace shuttles

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'shuttles': ['/home/firerazzer/Documents/TER/MONTRAC/catkin_ws/src/shuttles/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::shuttles::shuttle_idRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::shuttles::shuttle_idRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shuttles::shuttle_idRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shuttles::shuttle_idRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shuttles::shuttle_idRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shuttles::shuttle_idRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::shuttles::shuttle_idRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7bc20435b1237c98bd1aa24e06515eb0";
  }

  static const char* value(const ::shuttles::shuttle_idRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7bc20435b1237c98ULL;
  static const uint64_t static_value2 = 0xbd1aa24e06515eb0ULL;
};

template<class ContainerAllocator>
struct DataType< ::shuttles::shuttle_idRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "shuttles/shuttle_idRequest";
  }

  static const char* value(const ::shuttles::shuttle_idRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::shuttles::shuttle_idRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 robot\n\
int32 position\n\
";
  }

  static const char* value(const ::shuttles::shuttle_idRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::shuttles::shuttle_idRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct shuttle_idRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::shuttles::shuttle_idRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::shuttles::shuttle_idRequest_<ContainerAllocator>& v)
  {
    s << indent << "robot: ";
    Printer<int32_t>::stream(s, indent + "  ", v.robot);
    s << indent << "position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SHUTTLES_MESSAGE_SHUTTLE_IDREQUEST_H
