// Generated by gencpp from file shuttles/shuttle_id.msg
// DO NOT EDIT!


#ifndef SHUTTLES_MESSAGE_SHUTTLE_ID_H
#define SHUTTLES_MESSAGE_SHUTTLE_ID_H

#include <ros/service_traits.h>


#include <shuttles/shuttle_idRequest.h>
#include <shuttles/shuttle_idResponse.h>


namespace shuttles
{

struct shuttle_id
{

typedef shuttle_idRequest Request;
typedef shuttle_idResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct shuttle_id
} // namespace shuttles


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::shuttles::shuttle_id > {
  static const char* value()
  {
    return "4ce93559e67d465c0b309aaf61a7e04b";
  }

  static const char* value(const ::shuttles::shuttle_id&) { return value(); }
};

template<>
struct DataType< ::shuttles::shuttle_id > {
  static const char* value()
  {
    return "shuttles/shuttle_id";
  }

  static const char* value(const ::shuttles::shuttle_id&) { return value(); }
};


// service_traits::MD5Sum< ::shuttles::shuttle_idRequest> should match 
// service_traits::MD5Sum< ::shuttles::shuttle_id > 
template<>
struct MD5Sum< ::shuttles::shuttle_idRequest>
{
  static const char* value()
  {
    return MD5Sum< ::shuttles::shuttle_id >::value();
  }
  static const char* value(const ::shuttles::shuttle_idRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::shuttles::shuttle_idRequest> should match 
// service_traits::DataType< ::shuttles::shuttle_id > 
template<>
struct DataType< ::shuttles::shuttle_idRequest>
{
  static const char* value()
  {
    return DataType< ::shuttles::shuttle_id >::value();
  }
  static const char* value(const ::shuttles::shuttle_idRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::shuttles::shuttle_idResponse> should match 
// service_traits::MD5Sum< ::shuttles::shuttle_id > 
template<>
struct MD5Sum< ::shuttles::shuttle_idResponse>
{
  static const char* value()
  {
    return MD5Sum< ::shuttles::shuttle_id >::value();
  }
  static const char* value(const ::shuttles::shuttle_idResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::shuttles::shuttle_idResponse> should match 
// service_traits::DataType< ::shuttles::shuttle_id > 
template<>
struct DataType< ::shuttles::shuttle_idResponse>
{
  static const char* value()
  {
    return DataType< ::shuttles::shuttle_id >::value();
  }
  static const char* value(const ::shuttles::shuttle_idResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SHUTTLES_MESSAGE_SHUTTLE_ID_H
