// Generated by gencpp from file shuttles/shuttle_idResponse.msg
// DO NOT EDIT!


#ifndef SHUTTLES_MESSAGE_SHUTTLE_IDRESPONSE_H
#define SHUTTLES_MESSAGE_SHUTTLE_IDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace shuttles
{
template <class ContainerAllocator>
struct shuttle_idResponse_
{
  typedef shuttle_idResponse_<ContainerAllocator> Type;

  shuttle_idResponse_()
    : IdShuttle(0)  {
    }
  shuttle_idResponse_(const ContainerAllocator& _alloc)
    : IdShuttle(0)  {
  (void)_alloc;
    }



   typedef int32_t _IdShuttle_type;
  _IdShuttle_type IdShuttle;





  typedef boost::shared_ptr< ::shuttles::shuttle_idResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::shuttles::shuttle_idResponse_<ContainerAllocator> const> ConstPtr;

}; // struct shuttle_idResponse_

typedef ::shuttles::shuttle_idResponse_<std::allocator<void> > shuttle_idResponse;

typedef boost::shared_ptr< ::shuttles::shuttle_idResponse > shuttle_idResponsePtr;
typedef boost::shared_ptr< ::shuttles::shuttle_idResponse const> shuttle_idResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::shuttles::shuttle_idResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::shuttles::shuttle_idResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace shuttles

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'shuttles': ['/home/firerazzer/Documents/TER/MONTRAC/catkin_ws/src/shuttles/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::shuttles::shuttle_idResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::shuttles::shuttle_idResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shuttles::shuttle_idResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shuttles::shuttle_idResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shuttles::shuttle_idResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shuttles::shuttle_idResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::shuttles::shuttle_idResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39f3cc90c3f781e09c842cf3e85b7aa9";
  }

  static const char* value(const ::shuttles::shuttle_idResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39f3cc90c3f781e0ULL;
  static const uint64_t static_value2 = 0x9c842cf3e85b7aa9ULL;
};

template<class ContainerAllocator>
struct DataType< ::shuttles::shuttle_idResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "shuttles/shuttle_idResponse";
  }

  static const char* value(const ::shuttles::shuttle_idResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::shuttles::shuttle_idResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 IdShuttle\n\
\n\
";
  }

  static const char* value(const ::shuttles::shuttle_idResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::shuttles::shuttle_idResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.IdShuttle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct shuttle_idResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::shuttles::shuttle_idResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::shuttles::shuttle_idResponse_<ContainerAllocator>& v)
  {
    s << indent << "IdShuttle: ";
    Printer<int32_t>::stream(s, indent + "  ", v.IdShuttle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SHUTTLES_MESSAGE_SHUTTLE_IDRESPONSE_H
