// Generated by gencpp from file commande/Actionneurs.msg
// DO NOT EDIT!


#ifndef COMMANDE_MESSAGE_ACTIONNEURS_H
#define COMMANDE_MESSAGE_ACTIONNEURS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace commande
{
template <class ContainerAllocator>
struct Actionneurs_
{
  typedef Actionneurs_<ContainerAllocator> Type;

  Actionneurs_()
    : actionneurs(0)  {
    }
  Actionneurs_(const ContainerAllocator& _alloc)
    : actionneurs(0)  {
    }



   typedef int64_t _actionneurs_type;
  _actionneurs_type actionneurs;




  typedef boost::shared_ptr< ::commande::Actionneurs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::commande::Actionneurs_<ContainerAllocator> const> ConstPtr;

}; // struct Actionneurs_

typedef ::commande::Actionneurs_<std::allocator<void> > Actionneurs;

typedef boost::shared_ptr< ::commande::Actionneurs > ActionneursPtr;
typedef boost::shared_ptr< ::commande::Actionneurs const> ActionneursConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::commande::Actionneurs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::commande::Actionneurs_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace commande

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'commande': ['/home/etudiant/M1_ISTR/Ligne_transitique_MONTRAC/ros_ws/src/commande/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::commande::Actionneurs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::commande::Actionneurs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commande::Actionneurs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commande::Actionneurs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commande::Actionneurs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commande::Actionneurs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::commande::Actionneurs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a79d0b13aebfb5d0450ddf675b8fc68";
  }

  static const char* value(const ::commande::Actionneurs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a79d0b13aebfb5dULL;
  static const uint64_t static_value2 = 0x0450ddf675b8fc68ULL;
};

template<class ContainerAllocator>
struct DataType< ::commande::Actionneurs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "commande/Actionneurs";
  }

  static const char* value(const ::commande::Actionneurs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::commande::Actionneurs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 actionneurs\n\
\n\
\n\
";
  }

  static const char* value(const ::commande::Actionneurs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::commande::Actionneurs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.actionneurs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Actionneurs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::commande::Actionneurs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::commande::Actionneurs_<ContainerAllocator>& v)
  {
    s << indent << "actionneurs: ";
    Printer<int64_t>::stream(s, indent + "  ", v.actionneurs);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMANDE_MESSAGE_ACTIONNEURS_H
