// Generated by gencpp from file commande/bool_state.msg
// DO NOT EDIT!


#ifndef COMMANDE_MESSAGE_BOOL_STATE_H
#define COMMANDE_MESSAGE_BOOL_STATE_H

#include <ros/service_traits.h>


#include <commande/bool_stateRequest.h>
#include <commande/bool_stateResponse.h>


namespace commande
{

struct bool_state
{

typedef bool_stateRequest Request;
typedef bool_stateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct bool_state
} // namespace commande


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::commande::bool_state > {
  static const char* value()
  {
    return "c7a88ab7a85f83bcb882571b8469aebb";
  }

  static const char* value(const ::commande::bool_state&) { return value(); }
};

template<>
struct DataType< ::commande::bool_state > {
  static const char* value()
  {
    return "commande/bool_state";
  }

  static const char* value(const ::commande::bool_state&) { return value(); }
};


// service_traits::MD5Sum< ::commande::bool_stateRequest> should match 
// service_traits::MD5Sum< ::commande::bool_state > 
template<>
struct MD5Sum< ::commande::bool_stateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::commande::bool_state >::value();
  }
  static const char* value(const ::commande::bool_stateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::commande::bool_stateRequest> should match 
// service_traits::DataType< ::commande::bool_state > 
template<>
struct DataType< ::commande::bool_stateRequest>
{
  static const char* value()
  {
    return DataType< ::commande::bool_state >::value();
  }
  static const char* value(const ::commande::bool_stateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::commande::bool_stateResponse> should match 
// service_traits::MD5Sum< ::commande::bool_state > 
template<>
struct MD5Sum< ::commande::bool_stateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::commande::bool_state >::value();
  }
  static const char* value(const ::commande::bool_stateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::commande::bool_stateResponse> should match 
// service_traits::DataType< ::commande::bool_state > 
template<>
struct DataType< ::commande::bool_stateResponse>
{
  static const char* value()
  {
    return DataType< ::commande::bool_state >::value();
  }
  static const char* value(const ::commande::bool_stateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMANDE_MESSAGE_BOOL_STATE_H
