// Generated by gencpp from file commande/bool_stateRequest.msg
// DO NOT EDIT!


#ifndef COMMANDE_MESSAGE_BOOL_STATEREQUEST_H
#define COMMANDE_MESSAGE_BOOL_STATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace commande
{
template <class ContainerAllocator>
struct bool_stateRequest_
{
  typedef bool_stateRequest_<ContainerAllocator> Type;

  bool_stateRequest_()
    : query(false)  {
    }
  bool_stateRequest_(const ContainerAllocator& _alloc)
    : query(false)  {
    }



   typedef uint8_t _query_type;
  _query_type query;




  typedef boost::shared_ptr< ::commande::bool_stateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::commande::bool_stateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct bool_stateRequest_

typedef ::commande::bool_stateRequest_<std::allocator<void> > bool_stateRequest;

typedef boost::shared_ptr< ::commande::bool_stateRequest > bool_stateRequestPtr;
typedef boost::shared_ptr< ::commande::bool_stateRequest const> bool_stateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::commande::bool_stateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::commande::bool_stateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace commande

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'commande': ['/home/etudiant/M1_ISTR/Ligne_transitique_MONTRAC/ros_ws/src/commande/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::commande::bool_stateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::commande::bool_stateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commande::bool_stateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commande::bool_stateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commande::bool_stateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commande::bool_stateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::commande::bool_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d56f052dde9259c4dd003e064bd410a0";
  }

  static const char* value(const ::commande::bool_stateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd56f052dde9259c4ULL;
  static const uint64_t static_value2 = 0xdd003e064bd410a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::commande::bool_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "commande/bool_stateRequest";
  }

  static const char* value(const ::commande::bool_stateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::commande::bool_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool query\n\
";
  }

  static const char* value(const ::commande::bool_stateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::commande::bool_stateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.query);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct bool_stateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::commande::bool_stateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::commande::bool_stateRequest_<ContainerAllocator>& v)
  {
    s << indent << "query: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.query);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMANDE_MESSAGE_BOOL_STATEREQUEST_H
